version: '3.7'

services:
  tws:
    image: chris1204/interactivebroker-gateway

    env_file:
      - ./config/secrets.conf

    ports:
      # Gateway API connection
      - "4003:4003"
      # VNC
      - "5901:5900"

    volumes:
      - ./config/IBController.ini:/root/IBController/IBController.ini
      - ./config/jts.ini:/root/Jts/jts.ini

    environment:
      - TZ=America/Chicago
      - VNC_PASSWORD=1234 # CHANGE ME
      - TRADING_MODE=paper # either paper or live

  redis:
    image: redis:4.0.14-buster

    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

    ports:
      - '6379:6379'
